[package]

name = "base32"
version = "0.2.0"
authors = [ "Andreas Ots <qrpth@qrpth.eu>", "Tim Dumol <tim@timdumol.com>" ]
license = "MIT"
repository = "https://github.com/andreasots/base32"
description = "Base32 encoder/decoder for Rust"

[lib]

name = "base32"

[dev-dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
